
package au.net.electronichealth.ns.simd.tls.v2010;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "timeoutError", targetNamespace = "http://ns.electronichealth.net.au/smd/svc/SealedImmediateMessageDelivery/2010")
public class TimeoutErrorMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TimeoutErrorType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TimeoutErrorMsg(String message, TimeoutErrorType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TimeoutErrorMsg(String message, TimeoutErrorType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: au.net.electronichealth.ns.simd.tls.v2010.TimeoutErrorType
     */
    public TimeoutErrorType getFaultInfo() {
        return faultInfo;
    }

}
